name: Build and Deploy to Netlify
on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Deploy to Netlify
        id: deploy-to-netlify
        uses: kentaro-m/actions-netlify@develop
        with:
          publish-dir: './public'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      
      - name: Post a QR code for deploy url to the pull request
        uses: kentaro-m/qr-code-commenter-action@v0.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content: ${{ steps.deploy-to-netlify.outputs.deploy-url }}
          comment: |
            :lock: This is a QR code for access to the preview website.
            :iphone: Scan a code with your device.
            {qrcode}